apiVersion: apps/v1  ## for RS
kind: Deployment
metadata:
  name: mwadep
spec:
  replicas: 4
  ##strategy:
    ##type: RollingUpdate
  selector:
    matchLabels:  ## Equality Based
      app: myweb
  template:
    metadata:
      name: mwapod  ## pod name.  if we create more than 1 replica, this name won't be used
      labels:
        app: myweb
    spec:
      containers:
      - image: sreeni78/mywebapp:latest
        name: mwacon
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: mwadepsvc
spec:
  type: NodePort
  selector:
    app: myweb
  ports:
  - nodePort: 30009    ## node port
    targetPort: 8080   ## container port
    port: 9090         ## cluster ip port
